rest-client-config-data:
  url: "http://localhost:8080"
  todosGetPath: "/todos"
  todosPostPath: "/todos"
  todosPutPath: "/todos/{0}"
  todosDeletePath: "/todos/{0}"
  ssl: false
  enableHttpAttachments: false

to-do-app-in-docker:
  enabled: true
  logging: false
  imageName: "todo-app:latest"
  exposedPorts:
    8080: 4242

server:
  port: 8081

management.endpoints.web.exposure.include: '*'